title: 智能设备软件开发实训
baseurl: '/android'

disqus_short_name: zjsgsuandroid

defaults:
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page

exclude: [LICENSE, Gemfile, Gemfile.lock, README.md, vendor]

markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - disable_indented_code_blocks
    - autolink
    - strikethrough
    - space_after_headers
    - superscript
    - underline
    - highlight
    - quote
    - footnotes

sass:
    style: compressed
